[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.100.2"

[context.production]
    command = "hugo --gc --minify -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
